### PR TITLE
Update UIA mappings for ins and del

### PR DESCRIPTION
**Pull request by melanierichards**
What it says on the tin :)

For progress on #141

The following tasks have been completed:

 * [x] Confirmed there are no ReSpec/BikeShed errors or warnings.
 * [ ] Modified Web platform tests (link to pull request)

Implementation commitment:

 * [ ] WebKit (https://bugs.webkit.org/show_bug.cgi?id=)
 * [x] Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=)
 * [ ] Gecko (https://bugzilla.mozilla.org/show_bug.cgi?id=)

***
<a href="https://pr-preview.s3.amazonaws.com/melanierichards/html-aam/pull/206.html" title="Last updated on Jun 6, 2019, 9:43 PM UTC (90a7395)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/html-aam/206/b71b317...melanierichards:90a7395.html" title="Last updated on Jun 6, 2019, 9:43 PM UTC (90a7395)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@melanierichards, I’m a total noob to this area so hopefully this are not too silly questions... would I normally need to change something in Gecko to also support this (considering the indicated commitment in Blink above)? How can we check interoperability across browsers?

**Comment by melanierichards** [comment]
@marcoscaceres There are no silly questions! :D The "implementation commitment" section of the PR checklist I think is new, so I'll let @stevefaulkner @scottaohara speak to that, I just checked it for my UA. Mostly I'm providing the mappings for UIA that Scott will fold into a broader PR submitting mappings for `ins` and `del` on the various accessibility APIs.

I wouldn't expect you all on Gecko to make any changes for this PR specifically, unless you were to support UIA all-up. So just the MSAA + IA2 mappings would be pertinent for you w/r/t Windows accessibility APIs. Generally with AAMs, there are [WPT test suites](https://github.com/web-platform-tests/wpt) which seek to test each major UA + each accessibility API they support. I don't believe there's a test suite there for HTML-AAM but there is html5accessibility.com.

**Comment by LJWatson** [comment]
The implementation requirements for AAM are a little different from those of other specifications. For each feature in the AAM (role, state etc.) there should be at least two implementations for each of the acc API.
* IA2 is supported by Gecko and Chromium
* ATK is supported by WebkitGTK, Gecko, and Chromium
* AXAPI is supported by Webkit (Safari), Gecko, and Chromium
* UIA is supported in Edge

With regard to UIA, I believe there has been discussion about implementing UIA support in Chromium, though whether that remains an intent now Edge has switched to Chromium, or whether it is now more likely because microsoft is contributing to Chromium, I don't know. @melanierichards will likely know more. Either way it's an outlier in this case for the time-being.  

If the feature is not exposed correctly in a particular browser for a particular API (Chrome with IA2 for example), then a bug is filed in the relevant tracker.

We might want to update the PR template for this repo, so it has a list of available acc API implementations, plus a list of possible browser implementations for each API. @melanierichards will likely know more.

We do need to put together a test suite for this AAM. The rest of the AAM suite all have test suites, though in complete in at least one case. @marcoscaceres this is an area where your experience would be of great help.

**Comment by melanierichards** [comment]
@LJWatson @marcoscaceres 

UIA support in Chromium is actively underway, we're partnering with the Chromium community to complete that work. :)

I don't have context on the PR template, but if there's a discussion somewhere where you all would like implementer input, please let me know! I'm not aware of other WGs adding implementation commitments to PRs (neither do I claim to know everyone's process, though). It would be good to know if this is mostly as an FYI to the WG or if it's expected that you'd gate on commitments for a merge.

**Comment by LJWatson** [comment]
Marked as non substantive for IPR from ash-nazg.

**Pull request merged**
