### PR TITLE
feat: add UIA mappings for text edit maxlength

### PR DESCRIPTION
**Pull request by smhigley**
Part of the initial work for https://github.com/w3c/aria/issues/1119

I'm splitting out each API into a separate PR, because it looks like everything but UIA will need the addition of something new (probably something like a new object attribute), so I don't want to hold up any individual mapping while waiting for others to be discussed.

***
<a href="https://pr-preview.s3.amazonaws.com/smhigley/html-aam/pull/521.html" title="Last updated on Dec 4, 2023, 11:24 PM UTC (b010abd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/html-aam/521/ab38b66...smhigley:b010abd.html" title="Last updated on Dec 4, 2023, 11:24 PM UTC (b010abd)">Diff</a>

### CODE REVIEW

**Review by benbeaudry — APPROVED** [review]
LGTM. Thanks!

**Comment by douggeoffray** [comment]
Awesome!

**Comment by smhigley** [comment]
For more info:

- Edit supports RangeValue: https://learn.microsoft.com/en-us/windows/win32/winauto/uiauto-supporteditcontroltype (under  the "Required Control Patterns" heading)
- RangeValue pattern docs: https://learn.microsoft.com/en-us/windows/win32/winauto/uiauto-implementingrangevalue

**Comment by scottaohara** [comment]
this PR has been moved to https://github.com/w3c/aria/pull/2272

**Pull request closed without merging**
